//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PanaderiaDonMario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura_Inevntario
    {
        public int ID_FACTURAL { get; set; }
        public int ID_Inventario { get; set; }
        public int ID_Factura { get; set; }
        public Nullable<int> Cantidad { get; set; }
    
        public virtual Factura Factura { get; set; }
        public virtual Inventario Inventario { get; set; }
    }
}
