//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PanaderiaDonMario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        public Factura()
        {
            this.Factura_Inevntario = new HashSet<Factura_Inevntario>();
        }
    
        public int ID_Factura { get; set; }
        public System.DateTime fecha { get; set; }
        public double Total { get; set; }
        public string Cliente { get; set; }
        public int ID_User { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<Factura_Inevntario> Factura_Inevntario { get; set; }
    }
}
