//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PanaderiaDonMario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventario
    {
        public Inventario()
        {
            this.Factura_Inevntario = new HashSet<Factura_Inevntario>();
        }
    
        public int ID_Inventario { get; set; }
        public string Nombre { get; set; }
        public Nullable<double> Precio { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<Factura_Inevntario> Factura_Inevntario { get; set; }
    }
}
