//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PanaderiaDonMario.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PanaderiaEntities : DbContext
    {
        public PanaderiaEntities()
            : base("name=PanaderiaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Factura> Factura { get; set; }
        public DbSet<Factura_Inevntario> Factura_Inevntario { get; set; }
        public DbSet<Inventario> Inventario { get; set; }
        public DbSet<Usuario> Usuario { get; set; }
    }
}
